name: foobar-gen

dependencies:
- base >= 4.7 && < 5
- foobar

library:
  source-dirs: src
  dependencies:
  - genvalidity

tests:
  foobar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - foobar-gen
    - genvalidity-sydtest
    - sydtest
