name: dekking-report
version: 0.0.0.0
github: "NorfairKing/dekking"
author: "Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5


ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  ghc-options:
  # This must be put here and not lower because the tests use the plugin and
  # ghc detects that dekking-value is unused despite an import being generated
  # by the plugin.
  - -Wunused-packages
  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec
  - bytestring
  - containers
  - dekking-plugin
  - ghc
  - mtl
  - optparse-applicative
  - path
  - path-io
  - pretty-show
  - safe-coloured-text
  - text

executables:
  dekking-report:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -optP-Wno-nonportable-include-path # For macos
    dependencies:
    - dekking-report
