name: dekking-report
version: 0.0.0.0
github: "NorfairKing/dekking"
author: "Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- test_resources/**/*

ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec
  - bytestring
  - containers
  - dekking-value
  - dekking-plugin
  - filelock
  - ghc
  - mtl
  - optparse-applicative
  - path
  - path-io
  - pretty-show
  - safe-coloured-text
  - text

executables:
  dekking-report:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -optP-Wno-nonportable-include-path # For macos
    dependencies:
    - dekking-report

tests:
  dekking-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - dekking-report
    - dekking-value
    - path
    - path-io
    - sydtest
    - sydtest-aeson
