name: dekking-value
version: 0.0.0.0
github: "NorfairKing/dekking"
author: "Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - filelock

