name: dekking-value
version: 0.0.0.0
github: "NorfairKing/dekking"
author: "Tom Sydney Kerckhove"

# This package must have no dependencies, because then we can't run a
# code-coverage report for that dependency.
dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

