name: example

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - dekking-value
  - dekking-plugin

tests:
  example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - example
