name: dekking
version: 0.0.0.0
github: "NorfairKing/dekking"
author: "Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- test_resources/**/*

ghc-options:
- -Wall
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec
  - bytestring
  - ghc
  - mtl
  - path
  - path-io
  - pretty-show

executables:
  dekking:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -optP-Wno-nonportable-include-path # For macos
    dependencies:
    - dekking


tests:
  dekking-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dekking
    - sydtest
