name: syntax

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text

tests:
  syntax-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syntax
